// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe8j-Cc-vlpEemUFF8vnfi3idnR3yZwn8',
    appId: '1:681361124073:web:1117d43b8979ce5ba25e78',
    messagingSenderId: '681361124073',
    projectId: 'findhome-rental-home-solution',
    authDomain: 'findhome-rental-home-solution.firebaseapp.com',
    storageBucket: 'findhome-rental-home-solution.appspot.com',
    measurementId: 'G-WVNKF47KHK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXu9vzORMQoCExtcUdUvU-q8x4HHtCoMY',
    appId: '1:681361124073:android:3c82e12513d3bfa0a25e78',
    messagingSenderId: '681361124073',
    projectId: 'findhome-rental-home-solution',
    storageBucket: 'findhome-rental-home-solution.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfz7GVDV5nFtBGpEAkazi4Bsq9i5PGJkI',
    appId: '1:681361124073:ios:017c51ce034c2382a25e78',
    messagingSenderId: '681361124073',
    projectId: 'findhome-rental-home-solution',
    storageBucket: 'findhome-rental-home-solution.appspot.com',
    iosBundleId: 'com.example.findHome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfz7GVDV5nFtBGpEAkazi4Bsq9i5PGJkI',
    appId: '1:681361124073:ios:017c51ce034c2382a25e78',
    messagingSenderId: '681361124073',
    projectId: 'findhome-rental-home-solution',
    storageBucket: 'findhome-rental-home-solution.appspot.com',
    iosBundleId: 'com.example.findHome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBe8j-Cc-vlpEemUFF8vnfi3idnR3yZwn8',
    appId: '1:681361124073:web:e4401147d02233fea25e78',
    messagingSenderId: '681361124073',
    projectId: 'findhome-rental-home-solution',
    authDomain: 'findhome-rental-home-solution.firebaseapp.com',
    storageBucket: 'findhome-rental-home-solution.appspot.com',
    measurementId: 'G-E85482C36C',
  );
}
